# Generated by Django 2.0.4 on 2018-04-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0003_auto_20180317_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repo',
            name='user',
        ),
    ]
