# Generated by Django 2.0.4 on 2018-04-22 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0005_auto_20180422_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repo',
            name='category',
        ),
        migrations.DeleteModel(
            name='Repo',
        ),
    ]
