# Generated by Django 2.0.4 on 2018-04-22 20:56

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0006_auto_20180423_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('repo_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_username', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('git_last_modified', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('clone_url', models.TextField(blank=True, help_text='Do not edit.', null=True, validators=[django.core.validators.URLValidator()])),
                ('issues_url', models.TextField(blank=True, help_text='Do not edit.', null=True, validators=[django.core.validators.URLValidator()])),
                ('merges_url', models.TextField(blank=True, help_text='Do not edit.', null=True, validators=[django.core.validators.URLValidator()])),
                ('milestones_url', models.TextField(blank=True, help_text='Do not edit.', null=True, validators=[django.core.validators.URLValidator()])),
                ('comments_url', models.TextField(blank=True, help_text='Do not edit.', null=True, validators=[django.core.validators.URLValidator()])),
                ('commits_url', models.TextField(blank=True, help_text='Do not edit.', null=True, validators=[django.core.validators.URLValidator()])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repo.Category')),
            ],
        ),
    ]
