# Generated by Django 2.0.4 on 2018-04-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='git_token',
            field=models.CharField(max_length=255, verbose_name='Git token'),
        ),
    ]
